human_mouse_zebrafish:
	nextflow run czbiohub/nf-kmer-similarity -latest -profile aws \
		--samples s3://kmer-hashing/hematopoeisis/smartseq2/human_mouse_zebrafish/samples.csv


merkin2012:
	nextflow run czbiohub/nf-kmer-similarity -latest --sra "SRP016501" -profile aws
